config/routes.rb
Rails.application.routes.draw do
  resources :auctions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match '/importer',      to: 'importer#import',           via: 'get'
  match '/importer',      to: 'importer#import',        via: 'post'

  root to: "auctions#index"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  has_many :auction_locations
  has_many :auctions, through: :auction_locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :auction_locations
  has_many :addresses, through: :auction_locations
  has_many :bids
  has_many :stock


  def show
    respond_to do |format|
      format.js {render layout: false} 
    end
  end

end

app/models/auction_location.rb
class AuctionLocation < ApplicationRecord
  belongs_to :auction
  belongs_to :address
end

app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :auction
  belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :auction
  has_one :bid
  belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { render :new }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auction_params
      params.fetch(:auction, {})
    end
end

app/controllers/importer_controller.rb
class ImporterController < ApplicationController
  require 'csv'
  before_action :load_locals


  def import

    importer(params[:file])

    #if there was no file selected for import, inform the user
    if params.has_key?(:file)
      redirect_to root_url, notice: "Auction data imported."
    else
      redirect_to root_url, notice: "No file was selected."
    end
  end


  private

    def importer(file)

     if file
        CSV.foreach(file.path, headers: true) do |row|

          params_hash = row.to_hash 
         
          #variables to hold the params used to create/find each of the models to be used for this auction
          address_hash = {}
          vehicle_hash = {}
          auction_hash = {}
          stock_hash = {}
          bid_hash = {}
            
          #create temp variables to be using in parsing the params hash
          temp_auction = Auction.new
          temp_address = Address.new
          temp_vehicle = Vehicle.new
          temp_bid = Bid.new
          temp_stock = Stock.new

          #parse the params_hash for params specific to each needed model
          params_hash.each { |k, v| address_hash[k] = params_hash.delete(k) if temp_address.respond_to?(k) }      #parse parameters for address model
          params_hash.each { |k, v| vehicle_hash[k] = params_hash.delete(k) if temp_vehicle.respond_to?(k) }      #parse parameters for vehicle model
          params_hash.each { |k, v| auction_hash[k] = params_hash.delete(k) if temp_auction.respond_to?(k) }      #parse parameters for auction model
          params_hash.each { |k, v| bid_hash[k] = params_hash.delete(k) if temp_bid.respond_to?(k) }              #parese parameters for bid model
          params_hash.each { |k, v| stock_hash[k] = params_hash.delete(k) if temp_stock.respond_to?(k) }          #parse parameters for stock model

          #using the parsed params, find/create the necessary models to fill out the auction object
          vehicle = Vehicle.find_or_create_by!(vehicle_hash)        #find the vehicle matching the vehicle hash params, or create if does not exist
          address = Address.find_or_create_by!(address_hash)        #find the address matching the address hash params, or create if does not exist
   
          auction = Auction.find_or_create_by!(auction_hash)        #find the auction matching the auction hash params, or create if does not exist

          #there might be stock from different auctions that have the same vehicle stock number, so allow dupes between different auctions
          # and it may be possible that auctions reuse stock numbers after a vehicle is sold.
          #  so identify stock specifically by associated auction and vehicle 
          stock_hash[:auction_id] = auction.id
          stock_hash[:vehicle_id] = vehicle.id
          stock = Stock.find_or_create_by!(stock_hash) 

          #only one bid per stock for auction (only storing winning bid currently)
          bid_hash[:auction_id] = auction.id
          bid_hash[:stock_id] = stock.id
          bid = Bid.find_or_create_by!(bid_hash) do |new_bid|
            new_bid.profit = new_bid["winning bid"].to_i - new_bid["seller payout"].to_i    #calc car sale profit for store and easy later use
            new_bid.save
          end

          #leaving open the possibility that a location may have different auctions held at it at different times (for example, a county fairgrounds)
          # so using AuctionLocation to create the relationship between an auction and an address allowing for multiple auctions to use the same address 
          auction_location = AuctionLocation.find_or_create_by!(auction_id: auction.id, address_id: address.id) do |auction_location|
            auction_location.auction = auction
            auction_location.address = address
            auction_location.save
          end
 

        end
    end
  end

  def load_locals
    @auctions = Auction.all
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/views/auctions/_allStats.html.erb
<%# 
    partial used for displaying all of the needed stats for all auctions 
    input variables:
                    auctions: expects to be set to array of auctions that are to be displayed 
%> 

<h1>Auctions</h1>

<div class="text-center">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-sm-3 text-center">Auction name</th>
        <th class="col-sm-3 text-center">Auction city</th>
        <th class="col-sm-2 text-center">Vehicles Sold</th>
        <th class="col-sm-2 text-center">Total Profit</th>
        <th class="col-sm-2 text-center">Average Profit per Car</th>
      </tr>
    </thead>

    <tbody>
      <% auctions.each do |auction| %>                                    <%# loop through each of the auctions and display the pertinent stats in the table %>
        <tr>
          <td><%= link_to auction["auction name"], auction, remote: true %></td>
          <td>
            <% auction.auction_locations.each do |location| %>
              <%= location.address.city %>
            <% end %>
          </td>
          <td>
            <%= auction.stock.count %>
          </td>
          <td>
            <%= number_to_currency(auction.bids.sum(:profit)) %>          <%# sum up the total profit for the auction and display in proper format %>      
          </td>
          <td>
            <%= number_to_currency(auction.bids.average(:profit)) %>      <%# calc average profit per car for auction and display in proper format %>
          </td>


            
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

app/views/auctions/_auctions.html.erb
<h1>Auctions</h1>

<%# create a simple list of auction names with their cities %>
<table id="simpleAuctionListing">
  <thead>
    <tr>
      <th>Auction name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% auctions.each do |auction| %>            <%# loop through the auctions and display their name with associated citiers %>
      <tr>
        <td><strong><%= link_to auction["auction name"], auction, remote: true %></strong>       
          <% auction.auction_locations.each do |location| %>
            <%= location.address.city %>
          <% end %>
        
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/auctions/_form.html.erb
<%= form_for(auction) do |f| %>
  <% if auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% auction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auctions/_show.html.erb
<%# 
    partial used for listing out the single Auction details in a more stylized format 
    input variables:
                    auction: expects to be set to single auction object that is to be displayed 
%> 

<div>
  <div class="row">
    <div class="col-xs-2 col-sm-2">
      <strong>Auction name:</strong>
    </div>
    <div class="col-xs-2 col-sm-4">
      <%= auction["auction name"] %>
    </div>
  </div>
       
  <div class="row">
    <div class="col-xs-2 col-sm-2">
        <strong>City:</strong>
    </div>
    <div class="col-xs-2 col-sm-4">
          <% auction.auction_locations.each do |location| %>
            <%= location.address.city %>
          <% end %>
    </div>
  </div>
       
  <div class="row">
    <div class="col-xs-2 col-sm-2">
        <strong>Vehicles Sold:</strong>
    </div>
    <div class="col-xs-2 col-sm-4">
        <%= auction.stock.count %>                                      <%#count the total number of vehicles sold by this auction %>
    </div>
  </div>
       
  <div class="row">
    <div class="col-xs-2 col-sm-2">
        <strong>Total Auction Profit:</strong>
    </div>
    <div class="col-xs-2 col-sm-4">
        <%= number_to_currency(auction.bids.sum(:profit)) %>            <%# sum up the total profit for the auction and display in proper format %> 
    </div>
  </div>
       
  <div class="row">
    <div class="col-xs-2 col-sm-2">
        <strong>Average Profit/Car:</strong>
    </div>
    <div class="col-xs-2 col-sm-4">
        <%= number_to_currency(auction.bids.average(:profit)) %>        <%# calc average profit per car for auction and display in proper format %>
    </div>
  </div>
       
  <br>
   
  <%# list out all the stock for this auction in a stylized table %> 
  <h3>Stock</h3>
  <table class="table table-hover">
    <thead>
      <tr>
        <th class="col-sm-1 ">Stock #</th>
        <th class="col-sm-1 ">Year</th>
        <th class="col-sm-1 ">Make</th>
        <th class="col-sm-2 ">Model</th>
        <th class="col-sm-2 ">Profit</th>
        <th class="col-sm-5 ">Description</th>
      </tr>
    </thead>
      <tbody>
        <% auction.stock.each do |curStock| %>          <%# loop through the stock associated with this auction and display relevant information %>   
          <tr>
            <td><%= curStock['vehicle stock number'] %></td>
            <td><%= curStock.vehicle['vehicle year'] %></td>
            <td><%= curStock.vehicle['vehicle make'] %></td>
            <td><%= curStock.vehicle['vehicle model'] %></td>
            <td><%= number_to_currency(curStock.bid.profit) %></td>
            <td><%= curStock.description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid ">


  <% if @auctions.count > 0 %>
  <div id="auction_listings">
    <%= render partial: "auctions/auctions", locals: {auctions: @auctions}  %>
  </div>



  <div class="jumbotron" id="detail_view"> 
    <h3> Click auction name for more detail </h3>
    <h3> Click 'All Stats' in menu for complete listing </h3>
  </div>

  <% end %>
</div>

app/views/auctions/index.js.erb
$("#auction_listings").html("<%= escape_javascript(render partial: 'auctions/allStats', locals: { auctions: @auctions } ) %>");

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<%= render :partial => @auction %>

app/views/auctions/show.js.erb
$("#detail_view").html("<%= escape_javascript(render partial: 'auctions/show', locals: { auction: @auction } ) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AucStat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse" id="aucStatNav">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">AucStat</a>
        </div>
 
     <ul class="nav navbar-nav" >
      <li class="active"><a href="#">Home</a></li>                              
      <li>    <%= link_to 'All Stats', auctions_path, remote: true %> </li>     <%# button that will render the 'allStats' partial for complete table listing of all auctions %>
     </ul>

     </div>
    </nav>

    <div class="container-fluid">
      <div class="row content">
        <div class="col-sm-1 sidenav">          <%#sidenav div purely used for styling or potential future use %>
        </div>

        <div class="col-sm-10 "> 
          <div id="importdiv">
            <h3>Import a CSV File</h3>
            <%= form_tag({controller: "importer", action: "import"},  method: "post", multipart: true) do %>
                <%= file_field_tag :file %>
                <%= submit_tag("Import CSV", :class=>'btn-info') %>
              <% end %>
          </div>
          <%= yield %>
        </div>

        <div class="col-sm-1 sidenav">          <%#sidenav div purely used for styling or potential future use %>
        </div>

      </div>
    </div>

<footer class="container-fluid text-center">
  <p>Erik Hutchinson 2017</p>
</footer>
  </body>
</html>